/**
 * Turns scripts/photos/manifest.json into committed imagery:
 *
 *   public/images/photos/<key>.webp   3:4, 1200 × 1600, WebP q80 (products, tiles)
 *   public/images/photos/<key>.webp   16:9 or 4:5 for banners, per manifest
 *   prisma/seed/data/photos.ts        the mapping the seed reads, plus credits
 *   ASSETS.md                         the imagery table
 *
 * Source files come from Unsplash (unsplash.com/license). Each entry records
 * the photo id, photographer and page URL. Run after editing the manifest:
 *   node scripts/photos/download.mjs
 */
import { mkdir, readFile, writeFile, stat } from "node:fs/promises";
import path from "node:path";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const sharpDir = (await import("node:fs"))
  .readdirSync(path.join(root, "node_modules/.pnpm"))
  .find((d) => d.startsWith("sharp@"));
const sharp = require(path.join(root, "node_modules/.pnpm", sharpDir, "node_modules/sharp"));

const manifest = JSON.parse(
  await readFile(path.join(root, "scripts/photos/manifest.json"), "utf8"),
);
const outDir = path.join(root, "public/images/photos");
await mkdir(outDir, { recursive: true });

// Metadata for every photo id, from the search dumps.
const meta = new Map();
for (const file of (await import("node:fs"))
  .readdirSync(path.join(root, "scripts/photos/out"))
  .filter((f) => f.endsWith(".json"))) {
  for (const p of JSON.parse(await readFile(path.join(root, "scripts/photos/out", file), "utf8")))
    meta.set(p.id, p);
}

const SIZES = {
  portrait: { w: 1200, h: 1600 },
  banner: { w: 1600, h: 900 },
  tall: { w: 1200, h: 1500 },
};

// Review labels are read off a JPEG: ids may be truncated and O/0/Q or I/l/1 confused.
const fold = (v) => v.toLowerCase().replace(/[0oq]/g, "o").replace(/[il1]/g, "i");
function resolve(id) {
  if (meta.has(id)) return id;
  const keys = Array.from(meta.keys());
  let hits = keys.filter((k) => k.startsWith(id));
  if (hits.length !== 1) hits = keys.filter((k) => fold(k).startsWith(fold(id)));
  if (hits.length === 1) return hits[0];
  throw new Error(
    hits.length === 0 ? `No metadata for ${id}` : `Ambiguous id ${id}: ${hits.join(", ")}`,
  );
}

async function fetchPhoto(id) {
  const m = meta.get(id);
  if (!m) throw new Error(`No metadata for ${id}; run search.mjs for its subject first`);
  const url = `https://images.unsplash.com/${new URL(m.raw).pathname.slice(1)}?w=1800&q=90&fm=jpg`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${id}: ${res.status}`);
  return Buffer.from(await res.arrayBuffer());
}

const credits = new Map();
const files = new Map();

const blurs = {};

async function ensure(rawId, shape = "portrait") {
  const id = resolve(rawId);
  const key = `${id}-${shape}`;
  if (files.has(key)) return files.get(key);
  const size = SIZES[shape];
  const rel = `images/photos/${id}-${shape}.webp`;
  const abs = path.join(root, "public", rel);
  let exists = false;
  try {
    await stat(abs);
    exists = true;
  } catch {}
  if (!exists) {
    const bytes = await fetchPhoto(id);
    await sharp(bytes)
      .rotate()
      .resize(size.w, size.h, { fit: "cover", position: "attention" })
      .webp({ quality: 80 })
      .toFile(abs);
    await new Promise((r) => setTimeout(r, 200));
  }
  const m = meta.get(id);
  credits.set(id, {
    id,
    photographer: m.photographer,
    username: m.username,
    page: m.page,
    alt: m.alt,
  });
  files.set(key, `/${rel}`);
  // Blur placeholder: a 16px-wide WebP of the final crop, inlined.
  const tiny = await sharp(abs)
    .resize(16, Math.round((16 * size.h) / size.w))
    .webp({ quality: 40 })
    .toBuffer();
  blurs[`/${rel}`] = `data:image/webp;base64,${tiny.toString("base64")}`;
  return `/${rel}`;
}

// Products: { slug: { colors: { "Ink": ["id1","id2"], ... }, note?: string } }
const products = {};
for (const [slug, entry] of Object.entries(manifest.products)) {
  products[slug] = { colors: {}, note: entry.note ?? null };
  for (const [color, ids] of Object.entries(entry.colors)) {
    products[slug].colors[color] = [];
    for (const id of ids) products[slug].colors[color].push(await ensure(id, "portrait"));
    console.log(`${slug} / ${color}: ${ids.length} photo(s)`);
  }
}
const categories = {};
for (const [slug, id] of Object.entries(manifest.categories))
  categories[slug] = await ensure(id, "portrait");
const collections = {};
for (const [slug, id] of Object.entries(manifest.collections))
  collections[slug] = await ensure(id, "banner");
const banners = {};
for (const [id, spec] of Object.entries(manifest.banners))
  banners[id] = await ensure(spec.id, spec.shape ?? "banner");

const ts = `// Generated by scripts/photos/download.mjs from scripts/photos/manifest.json. Do not edit by hand.
export type PhotoCredit = { id: string; photographer: string; username: string; page: string; alt: string | null };

export const productPhotos: Record<string, { colors: Record<string, string[]>; note: string | null }> = ${JSON.stringify(products, null, 2)};

export const categoryPhotos: Record<string, string> = ${JSON.stringify(categories, null, 2)};

export const collectionPhotos: Record<string, string> = ${JSON.stringify(collections, null, 2)};

export const bannerPhotos: Record<string, string> = ${JSON.stringify(banners, null, 2)};

export const photoCredits: PhotoCredit[] = ${JSON.stringify(Array.from(credits.values()), null, 2)};

/** Inline blur placeholders keyed by image URL. */
export const photoBlur: Record<string, string> = ${JSON.stringify(blurs, null, 2)};
`;
await writeFile(path.join(root, "prisma/seed/data/photos.ts"), ts);

// ASSETS.md imagery table
const rows = Array.from(credits.values())
  .sort((a, b) => a.id.localeCompare(b.id))
  .map((c) => {
    const uses = [];
    for (const [slug, e] of Object.entries(products))
      for (const [color, urls] of Object.entries(e.colors))
        if (urls.some((u) => u.includes(`/${c.id}-`))) uses.push(`${slug} (${color})`);
    for (const [slug, url] of Object.entries(categories))
      if (url.includes(`/${c.id}-`)) uses.push(`category ${slug}`);
    for (const [slug, url] of Object.entries(collections))
      if (url.includes(`/${c.id}-`)) uses.push(`collection ${slug}`);
    for (const [id, url] of Object.entries(banners))
      if (url.includes(`/${c.id}-`)) uses.push(`banner ${id}`);
    return `| \`${c.id}\` | [${c.photographer}](https://unsplash.com/@${c.username}) | [photo](${c.page}) | Unsplash License | ${uses.join(", ")} |`;
  });
const table = `| Photo id | Photographer | Source | Licence | Used for |\n| --- | --- | --- | --- | --- |\n${rows.join("\n")}`;
let assets = await readFile(path.join(root, "ASSETS.md"), "utf8");
const marker = "<!-- photos:begin -->";
const endMarker = "<!-- photos:end -->";
const block = `${marker}\n${table}\n${endMarker}`;
assets = assets.includes(marker)
  ? assets.replace(new RegExp(`${marker}[\\s\\S]*?${endMarker}`), block)
  : assets + "\n" + block + "\n";
await writeFile(path.join(root, "ASSETS.md"), assets);
console.log(
  `${credits.size} photos, ${files.size} files written; prisma/seed/data/photos.ts and ASSETS.md updated`,
);
